---
##
# File:        tasks/main.yml
# Created:     12.08.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Nginx configuration tasks
##


- name: "Ensure all nginx packages are installed"
  become: true
  apt: 
      name: "{{ item }}"
      state: present
  with_items:
      - nginx




